language: java
jdk:
  -oraclejdk11
before_install:
  - sudo apt-get update
  - mvn clean package
script: docker-compose build
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script:
    docker tag organicos:latest "$DOCKER_USERNAME"/organicos:$TRAVIS_JOB_ID
    docker push "$DOCKER_USERNAME"/organicos
  on:
    branch: master
notifications:
  email: false

